#! /bin/bash

find -type f -name '*backup*' -delete

Rscript -e 'rmarkdown::render("README.Rmd")'

pandoc -s -o book/final_book.docx src/*.md

pandoc -s -o book/final_book.html src/*.md

pandoc -s -o book/final_book.md src/*.md --toc --standalone 
