---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r echo=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# SCREWTAPE2020

<!-- badges: start -->
<!-- badges: end -->


Repo for Screwtape2020 (working title) book
```{r include=FALSE}
library(tidyverse)
```
# The Book

## Build it

```
./build
```

## Read it
[Latest Build](book/final_book.md)


## Statistics

```{r include=FALSE}
getCount <- function(chapter) {
  
  text <- scan(paste0("src/",chapter), quote=NULL, what="x")
  result <- length(text)
  return(result)
  
}
```




```{r echo=FALSE}
chapters <- dir("src") 
chapters <- as.data.frame(chapters)

final <- chapters %>%
  dplyr::rowwise() %>% 
  dplyr::mutate(Word_Count = getCount(chapters)) %>% 
  dplyr::rename(Chapter = chapters)
 



```

```{r include=FALSE}
# Get draft status
source("draft_status.R")

final$Draft <- drafts

```


```{r echo=FALSE}

# Show final table
final %>% knitr::kable()

```


```{r echo=FALSE}
data.frame('Final Word Count' = sum(final$Word_Count)) %>% knitr::kable()
```



